---
title: "localized-network"
author: "devin"
date: "February 3, 2016"
output: html_document
---

```{r}
library(dplyr)
library(readr)
library(jsonlite)
library(lubridate)
library(knitr)
library(plotly)
```

```{r}
data <- fromJSON("prior_responses/users/vjd")
```

```{r}
flattened <- data$starredRepos[[length(data$starredRepos)]]
starredRepos <- data$starredRepos
starredRepos[[length(starredRepos)]] <- NULL
initial_df <- starredRepos %>% map(function(dat) {
  if (is.null(dat$language)) {
    dat$language <- NA
  }
  as_data_frame(dat)
}) %>% bind_rows()
flattened_df <- flattened %>% bind_rows
final_data <- bind_rows(initial_df, flattened_df)
```

```{r}
final_data
```

```{r}
final_data %>%
  group_by(owner) %>% 
  tally %>%
  filter(n > 1) %>% arrange(desc(n))
```

```{r}
final_data <- final_data %>%
  mutate(starred_dt = ymd_hms(final_data$starred_at),
         starred_day = ceiling_date(starred_dt, unit = "day"),
         starred_week = ceiling_date(starred_dt, unit = "week")
         )
```

```{r}
all_starred <- final_data %>% filter(!is.na(starred_at))
  
```

```{r}
all_starred %>%
  group_by(starred_day) %>%
  summarize(day_count = n()) %>% 
  mutate(cumsum = cumsum(day_count)) %>%
  ggplot(aes(x = starred_day, y = cumsum)) + geom_line(size =2) +
  theme_bw() + labs(x = "Date", y= "cumulative repositories starred")
```


```{r}
cummulative_w_lang <- all_starred %>%
  group_by(starred_day, language) %>%
  summarize(day_count = n()) %>% 
  ungroup %>%
  mutate(cumsum = cumsum(day_count)) %>%
  group_by(language) %>%
  mutate(cumsum_lang = cumsum(day_count))

repos_by_lang <- cummulative_w_lang %>% group_by(language) %>%
  summarize(repos_by_lang = max(cumsum_lang)) %>% arrange(desc(repos_by_lang))

repos_by_lang %>% 
  filter(repos_by_lang < 500) %>%
  ggplot(aes(x = repos_by_lang)) +
  geom_histogram(binwidth = 1, color = 'black', fill ="white") + theme_bw()

semi_join(cummulative_w_lang, 
          repos_by_lang %>% 
            filter(repos_by_lang > 10) %>%
            select(language))  %>%
  ggplot(aes(x = starred_day, y = cumsum)) + geom_line(size =1.5, alpha = 0.7) +
  theme_bw() + labs(x = "Date", y= "cumulative repositories starred") +
  geom_line(aes(y = cumsum_lang, color = language), size = 1.5)
```

```{r results='asis'}
repos_by_lang %>%
  filter(repos_by_lang > 10) %>% kable()
```

```{r}
results <- semi_join(cummulative_w_lang, 
          repos_by_lang %>% 
            filter(repos_by_lang > 10) %>%
            select(language))
# totals <- results %>% ungroup %>% distinct(starred_day) %>% mutate(language = "TOTAL")

results %>%# bind_rows(totals) %>% select(-day_count, cumsum) %>%
  ggplot(aes(x = starred_day, 
             y = cumsum_lang,
             group = factor(language),
             color = factor(language))) +
  geom_line() + geom_point() + 
  geom_line(aes(y = cumsum, group = NULL, color = "Total")) + 
  PKPDmisc::base_theme(axis_title_x = 20, axis_title_y = 20) + 
  theme_bw() + 
  labs(x = "Time", y = "Star count")

ggplotly()
```

```{r}
all_starred %>%
  filter(open_issues_count < 400) %>%
  ggplot(aes(x = open_issues_count)) + geom_histogram(color = "black", fill="white", binwidth=1 )
ggplotly()
```

